apiVersion: v2
name: edgehog
description: A Helm chart for Edgehog, the Open Source Device Manager Platform by SECO Mind
type: application
version: 0.3.0
appVersion: "0.13.1"
kubeVersion: ">=1.23.0-0"
home: https://edgehog.io
icon: https://raw.githubusercontent.com/edgehog-device-manager/docs/refs/heads/main/0.8/assets/logo.png
sources:
  - https://github.com/edgehog-device-manager/edgehog
keywords:
  - edgehog
  - iot
  - device-management
  - astarte
maintainers:
  - email: luca.zaninotto@secomind.com
    name: luser
  - email: luca.marchiori@secomind.com
    name: lucamarchiori
  - email: guilherme.crocetti@secomind.com
    name: guicrocetti
annotations:
  license: Apache-2.0
