{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled .Values.ingress.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "edgehog.fullname" . }}-tls
  labels:
    {{- include "edgehog.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  dnsNames:
    - {{ required "frontend.host is required" .Values.frontend.host }}
    - {{ required "backend.host is required" .Values.backend.host }}
    {{- if .Values.forwarder.enabled }}
    - {{ required "forwarder.host is required when forwarder.enabled is true" .Values.forwarder.host }}
    {{- end }}
  issuerRef:
    {{- toYaml .Values.ingress.tls.certManager.issuerRef | nindent 4 }}
{{- end }}
