{{- if and .Values.openfga.enabled .Values.openfgaInitJob.enabled (eq .Values.authorization.provider "openfga") (not .Values.authorization.existingStoreSecret) (not .Values.authorization.storeId) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edgehog.fullname" . }}-fga-model
  labels:
    {{- include "edgehog.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-6"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
data:
  {{- range $path, $_ := .Files.Glob "files/fga/**" }}
  {{ replace "/" "-" (trimPrefix "files/fga/" $path) }}: {{ $.Files.Get $path | quote }}
  {{- end }}
{{- end }}
